

Executing test function test_exception  ... Error in loadNamespace(name) : there is no package called ‘fakemake’
 done successfully.

